### ISSUE TITLE
Soft assertion

### ISSUE THREAD

**Issue by onlybiju** [fslev/json-compare#5]
Hello Team,
Thanks a lot for excellent json comparison tool...But can I suggest for an enhancement?

Would you please be able to implement soft assertion while doing JSON comparison? 
For example, we are comparing 2 JSON files  JSON A and JSON B. Both are having 10 fields. suppose while comparing something doesn't matches at 2nd field, the code stops over here and it doesn't compares rest of the 8 fields. Is there is any way we can compare rest of the 8 fields?
Please let me know if this can be done as enhancement?

Thank you!
Biju

**Comment by fslev** [comment]
I believe you are referring to showing all differences between the two json objects and not stop at the first one encountered. 
Sure, this is a good idea.
Implementing this isn't quite a walk in the park, since there are a lot of scenarios that need to be covered.
I believe that something similar to XML Unit, should be in place:
https://www.baeldung.com/xmlunit2#2-detailed-difference-example

You can also submit a pull request with the new feature.

**Comment by onlybiju** [comment]
Thank you! Will try to implement

**Comment by fslevoaca-ionos** [comment]
Implemented soft assertion support by checking all JSON diffs.
Differences are exposed inside the AssertionError message
Released new json-compare major version inside Maven central repo.
